import { Router, Request, Response } from "express";
import { prisma } from "../lib/prisma.js";
import { authMiddleware, requireRole } from "../middleware/auth.middleware.js";
import { productImageSchema, productSchema } from "../schemas/product.schema.js";
import { z } from "zod";
import { upload } from "../utils/fileUpload.js";
import fs from "fs";

const fieldErrors = (error: z.ZodError) => z.flattenError(error).fieldErrors;
const router = Router();

// GET /api/products
router.get("/", async (_req: Request, res: Response) => {
  const products = await prisma.product.findMany();
  res.json(products);
});

router.post(
  "/create",
  authMiddleware,
  requireRole("ADMIN"),
  
  async (req: Request, res: Response) => {
    try {
      const dataToValidate = {
        ...req.body,
        // image: req.file?.filename, // Grab the unique filename generated by Multer
      };
      const parsedData = productSchema.safeParse(dataToValidate);
      if (!parsedData.success) {
        if (req.file) {
          fs.unlinkSync(req.file.path);
        }
        return res.status(400).json({ error: fieldErrors(parsedData.error) });
      }
      const { name, description, price, stock, category } = parsedData.data;
      const userId = Number(req.user?.id);
      const product = await prisma.product.create({
        data: { name, description, price, stock, category, adminId: userId },
      });

      if (!product) {
        return res.status(400).json({ error: "Product creation failed" });
      }

      res.status(201).json(product);
    } catch (error) {
      res.status(500).json({ error: "Internal Server Error" });
    }
  },
);

router.patch(
  "/upload-image/:id",
  authMiddleware,
  requireRole("ADMIN"),
  upload.single("image"),
  async (req: Request, res: Response) => {
    const productId = Number(req.params.id);
    const dataToValidate = {
      image: req.file?.filename, // Grab the unique filename generated by Multer
    };
    const parsedData = productImageSchema.safeParse(dataToValidate);
    if (!parsedData.success) {
      if (req.file) {
        fs.unlinkSync(req.file.path);
      }
      return res.status(400).json({ error: fieldErrors(parsedData.error) });
    }
    try {
      const updatedProduct = await prisma.product.update({
        where: { id: productId },
        data: { image: parsedData.data.image },
      });
      res.json(updatedProduct);
    } catch (error) {
      res.status(500).json({ error: "Internal Server Error" });
    }
  },
);

export default router;
